# Generated by Django 4.2 on 2026-08-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_note_notetag_codeblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='snippet',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
